included:
  - "KitchenConnect"
  - "KitchenConnectTests"
  - "KitchenConnectUITests"
excluded:
  - "Pods"
  - "Carthage"
  - "DerivedData"
  - "Frameworks"
analyzer_rules:
  - unused_import
disabled_rules:
  - identifier_name
  - line_length
  - strict_fileprivate
opt_in_rules:
  - empty_count
  - trailing_closure
  - force_unwrapping
  - fatal_error_message
  - file_length
  - function_body_length
  - type_body_length
  - vertical_whitespace
  - private_outlet
  - private_action
  - implicitly_unwrapped_optional
  - notification_center_detachment
  - compiler_protocol_init
  - switch_case_alignment
  - syntactic_sugar
  - weak_delegate
